### ISSUE TITLE
Passing None for data results in compile error

### ISSUE THREAD

**Issue by jwilm** [jwilm/json-request#1]
[`request`](https://github.com/jwilm/json-request/blob/master/src/lib.rs#L143) is declared as

``` rust
pub fn request<S, D>(method: Method, url: &str, data: Option<S>) -> Result<Option<D>>
```

The compiler errors when `data` is `None` because now the type `S` is undefined.

```
error: unable to infer enough type information about `_`; type annotations or generic parameter binding required
```

There is a failing test [here](https://github.com/jwilm/json-request/blob/issue-1/tests/lib.rs#L78-L84) which demonstrates the desired behavior.

**Comment by jwilm** [comment]
Failing test is [here](https://github.com/jwilm/json-request/blob/issue-1/tests/lib.rs#L78-L84). The `request` implementation is [here](https://github.com/jwilm/json-request/blob/master/src/lib.rs#L143)

**Comment by bluss** [comment]
The type `S` matters, so it must be inferred somehow. In the future, with type param defaults properly turned on, you can set a default. For now you must choose a type, for example by hinting on the none: `None::<Xyz>`.

**Comment by jwilm** [comment]
What do you mean here?

> with type param defaults properly turned on

Is that an upcoming language feature?

**Comment by bluss** [comment]
Yep, see rust-lang/rust/issues/27336

It's an existing unstable feature, not stable yet.

**Comment by jwilm** [comment]
Thanks for the link.

_reads_
